export const FETCH_CHATGPT_ANSWER_REQUEST = 'FETCH_CHATGPT_ANSWER_REQUEST';
export const FETCH_CHATGPT_ANSWER_SUCCESS = 'FETCH_CHATGPT_ANSWER_SUCCESS';
export const FETCH_CHATGPT_ANSWER_FAIL = 'FETCH_CHATGPT_ANSWER_FAIL';

export const fetchChatGPTResponse = (prompt) => ({
    type: FETCH_CHATGPT_ANSWER_REQUEST,
    prompt
});
